# Code Audit

A full overview of the codebase, evaluating the workflow and systems. Problematic functions are highlighted and alternatives are proposed

# Utils

## base Utils
The different utility functions, and why they exist

In [2]:
from context import geomapi
import geomapi.utils as ut
import numpy as np
%load_ext autoreload
%autoreload 2

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


### `def get_min_average_and_max_value()`

In [3]:
# Useless function, nowhere used, you can just get the min, max and average separately
ut.get_min_average_and_max_value([[1,2,3]])

AttributeError: 'list' object has no attribute 'flatten'

### `def get_rotation_matrix_from_forward_up()`

Define a rotation based on the forward and up vector

In [12]:
print(ut.get_rotation_matrix_from_forward_up(np.array([0,0,1]), np.array([0,1,0])))
print(ut.get_rotation_matrix_from_forward_up(np.array([0,0,-1]), np.array([0,1,0])))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]


### `def convert_to_homogeneous_3d_coordinates()`

- why always return a 2D array?
- what if already homogeneous, but not 1 at the end? -> normalise

In [20]:
print(ut.convert_to_homogeneous_3d_coordinates([[1,1,5,1],[1,2,3,2]]))
print(ut.convert_to_homogeneous_3d_coordinates([1,1,5]))

[[1.  1.  5.  1. ]
 [0.5 1.  1.5 1. ]]
[[1. 1. 5. 1.]]


### `def get_geomapi_classes()`

What is the use for this?

In [ ]:
# What is the use for this?
ut.get_geomapi_classes()

[rdflib.term.URIRef('https://w3id.org/geomapi#Node'),
 rdflib.term.URIRef('https://w3id.org/geomapi#SetNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#PointCloudNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#MeshNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#LineSetNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#BIMNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#ImageNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#OrthoNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#PanoNode'),
 rdflib.term.URIRef('https://w3id.org/geomapi#RelativePart'),
 rdflib.term.URIRef('https://w3id.org/geomapi#AbsolutePart'),
 rdflib.term.URIRef('https://w3id.org/geomapi#Analysis'),
 rdflib.term.URIRef('https://w3id.org/geomapi#Result')]

### `def get_folder()`

2 functions exist

In [ ]:
print(ut.get_folder(r"C:\Users\jelle\Documents\DoctoraatLocal\geomapi\examples\Code_audit.ipynb"))
print(ut.get_folder_path(r"C:\Users\jelle\Documents\DoctoraatLocal\geomapi\examples\Code_audit.ipynb")) # deleted

C:\Users\jelle\Documents\DoctoraatLocal\geomapi\examples
C:\Users\jelle\Documents\DoctoraatLocal\geomapi\examples


### `def get_timestamp()`

The timestamp of a file should be when it is created, not when it is modified
this works on windows, but not on linux, since there is no build in function for that

In [16]:
print(ut.get_timestamp(r"C:\Users\jelle\Documents\DoctoraatLocal\geomapi\examples\Code_audit.ipynb"))
print(ut.get_timestamp("string"))

2025-03-12T14:08:33


ValueError: Path does not exist

### `def literal_to_python()`

Literals are pretty much always strings
to python only converts them to float or int, to number seems more appropriate

In [ ]:
print(ut.literal_to_python("10"))

1.0
1.0
10


### `def literal_to_list()`

In [51]:
print(ut.string_to_list("[1,2,3]")[0])
print(ut.literal_to_list("[5,ei,5.0]"))
print(ut.literal_to_list(5.0))

1
[5, 'ei', 5.0]
[5.0]


### `def cartesianTransform_to_literal()` 'featured3d_to_literal()'
This is obsolete

### `def validate_timestamp()`

In [ ]:
import dateutil.parser
dateutil.parser.parse("Tue Dec  7 09:38:13 2021")

datetime.datetime(2021, 12, 7, 9, 38, 13)

In [ ]:
# Beter om default datetime terug te geven, zo kan de precisie ook bewaard blijven
from datetime import datetime
#string
print(ut.validate_timestamp("2022:03:13 13:55:26", asStr=False),"2022-03-13T13:55:26")
#string
print(ut.validate_timestamp('Tue Dec  7 09:38:13 2021'),"2021-12-07T09:38:13")
#string
print(ut.validate_timestamp("1648468136.033126", millies=True),"2022-03-28T11:48:56.033126")
#datetime object
print(ut.validate_timestamp(datetime(2022,3,13,13,55,26)),"2022-03-13T13:55:26")


2022-03-13 13:55:26 2022-03-13T13:55:26
2021-12-07T09:38:13 2021-12-07T09:38:13
2022-03-28T11:48:56.033126 2022-03-28T11:48:56.033126
2022-03-13T13:55:26 2022-03-13T13:55:26


### `def check_if_subject_is_in_graph()`

In [26]:
from rdflib import Graph
imgGraphPath= r"C:\Users\jelle\Documents\DoctoraatLocal\geomapi\tests\testfiles\graphs\mesh_graph.ttl"
imgGraph=Graph().parse(str(imgGraphPath))
for s in imgGraph.subjects():
    print(s)

http://meshes#parking
http://meshes#parking
http://meshes#road
http://meshes#railway
http://meshes#road
http://meshes#railway
http://meshes#parking
http://meshes#parking
http://meshes#railway
http://meshes#parking
http://meshes#railway
http://meshes#parking
http://meshes#road
http://meshes#parking
http://meshes#parking
http://meshes#railway
http://meshes#parking
http://meshes#parking
http://meshes#road
http://meshes#road
http://meshes#road
http://meshes#railway
http://meshes#railway
http://meshes#parking
http://meshes#parking
http://meshes#road
http://meshes#road
http://meshes#railway
http://meshes#road
http://meshes#road
http://meshes#railway
http://meshes#road


### `def get_xsd_datatypes()` `get_ifcopenshell_class_name()`

nut hiervan?

## CADUtils

In [ ]:
from context import geomapi
import geomapi.utils.cadutils as cu
import numpy as np
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


1.0

### `calculate_perpendicular_distance()`

perpendicular is loodrecht. de afstand tussen 2 loodrechte lijnen is altijd 0
at is deze functie wordt berekend is de kleinst afstand tussen het snijpunt van de lijnen en het startpunt van beide lijnen

In [ ]:
point1 = [2,2]
point2 = [0,0]
point3 = [0,1]
point4 = [1,1]
distance = 1
cu.calculate_perpendicular_distance([point1, point2],[point3, point4])

### `mesh_to_o3d()`

not implemented

### `get_linesets_inliers_in_box()`

this function seems to require too many inputs that can be calculated itself, if this is usefull at all

In [ ]:
import open3d as o3d

cu.get_linesets_inliers_in_box()

points = o3d.utility.Vector3dVector([[0,0,0],[1.0,0,0]])
lines = o3d.utility.Vector2iVector([[0,1]])
lineset = o3d.geometry.LineSet(points = points, lines = lines)
cu.sample_pcd_from_linesets([lineset])


1.0
10
[array([0., 0., 0.]), array([0.1, 0. , 0. ]), array([0.2, 0. , 0. ]), array([0.3, 0. , 0. ]), array([0.4, 0. , 0. ]), array([0.5, 0. , 0. ]), array([0.6, 0. , 0. ]), array([0.7, 0. , 0. ]), array([0.8, 0. , 0. ]), array([0.9, 0. , 0. ]), array([1., 0., 0.])]


(PointCloud with 11 points.,
 array([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]))

## Geometry Utils

Geometryutils has a lot of functions, They can be filtered and grouped

In [3]:
from geomapi.utils import geometryutils as gmu

### `crop_mesh_by_convex_hull()`

This function requires a trimesh mesh, while all the others are open3d

In [ ]:
gmu.crop_mesh_by_convex_hull()

### `get_points_and_normals()`

- why added transform?
- only half finished

In [ ]:
gmu.get_points_and_normals()

### `gmu.compute_nearest_neighbor_with_normal_filtering()`

Combine the 2 functions

In [ ]:
from geomapi.utils import geometryutils as gmu
gmu.compute_nearest_neighbor_with_normal_filtering()
gmu.compute_nearest_neighbors()

### Distance querries

I think we can reduse this by a lot
- filter_geometry_by_distance (source, target, distance)
- filter_geometry(source, target)

In [ ]:
gmu.create_visible_point_cloud_from_meshes()
gmu.crop_dataframe_from_meshes()
gmu.crop_geometry_by_box()
gmu.crop_geometry_by_distance() # Returns the portion of a pointcloud that lies within a range of another mesh/point cloud.
gmu.crop_geometry_by_raycasting()
gmu.crop_mesh_by_convex_hull() # trimesh cropping
gmu.crop_point_cloud_from_meshes()
gmu.filter_geometry_by_distance() # selects parts of a geometry that are within a certain distance from a single point
gmu.filter_pcd_by_distance() # selects the points that are within a certain distance from the other pointcloud
gmu.get_box_inliers()
gmu.get_box_intersections()
gmu.get_mesh_inliers()
gmu.get_pcd_collisions()
gmu.get_indices_in_hull()
gmu.get_points_in_hull() # returns points inside and outside convex hull

### `get_mesh_representation()`

just converts to convex hull of pointcloud

In [ ]:
gmu.get_mesh_representation()

### `project_meshes_to_rgbd_images()`

- I feel this works better as a tool function to fill a bunch of image nodes from a mesh and cam parameters
- also why is this not just a screenshot function in open3d?

In [ ]:
import open3d
gmu.project_meshes_to_rgbd_images()
# vb: open3d.visualization.rendering.OffscreenRenderer().render_to_depth_image()

### `get_data3d_from_pcd()`
- fix function name to indicate E57

In [ ]:
gmu.get_data3d_from_pcd()

### `describe_element()`

- very vague function name
- Takes the columns of a dataframe and builds a ply-like description.

In [ ]:
gmu.describe_element()

### `img_to_arrays()`
- should be in imageutils, also just reads an image
- what is tasknummer??, purely for multiprocessing (put it in a wrapper function?)

In [ ]:
gmu.img_to_arrays()

def number_function(nr: int, func, *args):
    return nr, func(*args)

### `generate_visual_cone_from_image()`
- create frustrum instead

In [ ]:
gmu.generate_visual_cone_from_image()

### `get_convex_hull()`

- convex hulls of 2D objects should either be a fixed offset box or a 2d shape, not a randomly slightly enlarged box

In [6]:
gmu.get_convex_hull(np.array([[0,0,0],[1,0,0],[2,0,0]]))

RuntimeError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)

While executing:  | qhull Qt
Options selected for Qhull 2020.2.r 2020/08/31:
  run-id 491205220  Qtriangulate  _pre-merge  _zero-centrum  _max-width  2
  Error-roundoff 1.8e-15  _one-merge 1.3e-14  _near-inside 6.3e-14
  Visible-distance 3.6e-15  U-max-coplanar 3.6e-15  Width-outside 7.2e-15
  _wide-facet 2.1e-14  _maxoutside 1.4e-14

precision problems (corrected unless 'Q0' or an error)
      4 degenerate hyperplanes recomputed with gaussian elimination
      4 nearly singular or axis-parallel hyperplanes
      4 zero divisors during back substitute
      4 zero divisors during gaussian elimination

The input to qhull appears to be less than 3 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p3(v4):     0     0     0
- p1(v3):     1     0     0
- p2(v2):     2     0     0
- p0(v1):     0     0     0

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 1.8e-15.  The center point, facets and distances
to the center point are as follows:

center point     0.75        0        0

facet p1 p2 p0 distance=    0
facet p3 p2 p0 distance=    0
facet p3 p1 p0 distance=    0
facet p3 p1 p2 distance=    0

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:         0         2  difference=    2
  1:         0         0  difference=    0
  2:         0         0  difference=    0

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 1.8e-15.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.


### `get_oriented_bounding_box()`
- same as convex hull

In [27]:
from geomapi.utils import geometryutils as gmu
import quaternion
# Test with parameters (center, extent, euler_angles)
parameters = np.array([
    [4, 5, 6],  # Center
    [1, 2, 3],  # Extent
    [0, np.pi, 0]   # Euler angles (no rotation)
])
obb = gmu.get_oriented_bounding_box(parameters)
print(obb.R)
quaternion.as_euler_angles(quaternion.from_rotation_matrix(obb.R)) * 180/np.pi

[[-1.0000000e+00  0.0000000e+00  1.2246468e-16]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00]
 [-1.2246468e-16  0.0000000e+00 -1.0000000e+00]]


array([ 180.,  180., -180.])

In [ ]:
# going back and forth to eulers can change rotations, except for very basic ones like 90 deg
center = [0, 0, 0]
extent = [1, 2, 3]
euler_angles = [90, 0, 0]
euler_angles2 = [60, 80, 60]

obb = gmu.get_oriented_bounding_box(np.array([center, extent, euler_angles]), True)
obb2 = gmu.get_oriented_bounding_box(np.array([center, extent, euler_angles2]), True)
print(gmu.get_oriented_bounding_box_parameters(obb))
print(gmu.get_oriented_bounding_box_parameters(obb2))


The euler angles are derived from the rotation matrix, please note that this representation has a number of disadvantages
[ 0.  0.  0.  1.  2.  3. 90.  0.  0.]
The euler angles are derived from the rotation matrix, please note that this representation has a number of disadvantages
[  0.           0.           0.           1.           2.
   3.          84.23136778 -30.25159748  84.23136778]


### `create_ellipsoid_mesh()`
- why does this exist?
-monkey patch into open3d?

In [ ]:
gmu.create_ellipsoid_mesh()

### Geometric operators

- join_geometries (booleans)
  - intersection
  - union
  - difference

In [ ]:
gmu.join_geometries()

## ImageUtils

In [7]:
from geomapi.utils import imageutils as iu

### `calculateGSD()`
- tools or in ImageNode 

In [ ]:
iu.calculateGSD()

### HED Line detection

Tools if anywhere

In [ ]:
iu.detect_hed_lines()

### `fill_black_pixels()`

- function name unclear
- edge detection cleanup?

In [ ]:
iu.fill_black_pixels()

In [ ]:
from geomapi.nodes import ImageNode

node = ImageNode()

node.world_to_pixel_coordinates([0,0,1])

array([[240.],
       [320.]])

### Image matching pipeline

In [ ]:
iu.match_images()

# Nodes

## PanoNode

In [ ]:
_cartesianTransform = None
if _cartesianTransform is None:
    #you could initialize a pano in an upright position instead of forward to match a terrestrial vantage point
    rotation_matrix_90_x=np.array( [[ 1, 0, 0.],
                                    [ 0, 0,-1 ],
                                    [ 0, 1, 0 ]])  
    _cartesianTransform = gmu.get_cartesian_transform(rotation=rotation_matrix_90_x)    

# Tools

## Base Tools

In [34]:
from geomapi import tools
import open3d as o3d
cloud = o3d.geometry.PointCloud()
tools.create_node(resource = cloud)

ValueError: Resource type not supported or len(resource.points) <3.