# SESSION TO GRAPH
In this notebook, we merge multiple sources in a sessionNode
For every resource, its respective NODE type is created after which a joint sessionNode is created 
that governs the metadata of the resources 
As ouput, the method generates an RDF GRAPH (.ttl) 

>This codebase operates on the scan2bim2.yml environment (python 3.8) and ifcopenshell

In [1]:
#IMPORT PACKAGES
from rdflib import Graph
import os.path
import importlib
import numpy as np
import xml.etree.ElementTree as ET
import open3d as o3d
import uuid    
import pye57 
import ifcopenshell
import ifcopenshell.geom as geom
import ifcopenshell.util
import ifcopenshell.util.selector
import sys
#IMPORT MODULES
from context import geomapi 
from geomapi.nodes import *
from geomapi.utils import *
import geomapi.tools as tl


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
%load_ext autoreload

In [3]:
%autoreload 2

## 1. INITIALIZE SESSION

In [4]:
## INPUTS
projectPath= os.path.abspath(os.path.join(os.getcwd(), os.pardir))+"\\tests"#"D:\\Data\\2018-06 Werfopvolging Academiestraat Gent" 
sessionPath = projectPath + "\\Samples7" #"K:\Projects\2025-03 Project FWO SB Jelle\7.Data\21-11 House Maarten\RAW data\session_22-03-13 canon
graphPath=sessionPath + "\\sessionGraph.ttl"
remark1='remark'

meshPath=sessionPath+"\\mesh.obj"
imgPath=sessionPath+"\\IMG_2174.JPG"
pcdPath=sessionPath+"\\pointcloud.pcd"
ifcPath=sessionPath+"\\012103-07-BIM-Zwevegem Brucqstraat.ifc"

## 2. CREATE DATA NODES


In [5]:

meshNode=MeshNode(path=meshPath,getResource=True, remark1=remark1)
imgNode=ImageNode(path=imgPath,getResource=True, remark1=remark1)
pcdNode=PointCloudNode(path=pcdPath,getResource=True, remark1=remark1)
# ifcNodes=tl.ifc_to_nodes(ifcPath=ifcPath,getResource=True,remark1=remark1)

nodeList=[meshNode,imgNode,pcdNode]

mesh=meshNode.mesh
img=imgNode.image
pcd=pcdNode.pcd
resources=[mesh,img,pcd]
print(resources)

[TriangleMesh with 4735 points and 9581 triangles., array([[[168, 154, 136],
        [168, 154, 136],
        [169, 153, 136],
        ...,
        [ 27,  24,  26],
        [ 25,  22,  24],
        [ 20,  19,  21]],

       [[168, 154, 136],
        [168, 154, 136],
        [169, 153, 136],
        ...,
        [ 27,  24,  26],
        [ 24,  21,  23],
        [ 20,  19,  21]],

       [[168, 154, 136],
        [168, 154, 136],
        [169, 153, 136],
        ...,
        [ 26,  23,  25],
        [ 22,  21,  23],
        [ 19,  21,  22]],

       ...,

       [[ 63,  75,  81],
        [ 63,  75,  81],
        [ 64,  76,  82],
        ...,
        [ 65,  73,  73],
        [ 65,  73,  73],
        [ 66,  74,  74]],

       [[ 63,  75,  79],
        [ 63,  75,  81],
        [ 64,  76,  82],
        ...,
        [ 65,  73,  73],
        [ 64,  72,  72],
        [ 65,  73,  73]],

       [[ 64,  76,  80],
        [ 64,  76,  82],
        [ 64,  76,  82],
        ...,
        [ 64,  71,  74

In [6]:
sessionNode0=SessionNode(subject='mySession')
print('test with nodes: '+ sessionNode0.subject)

sessionNode5=SessionNode(linkedNodes=nodeList)
print('test with nodes: '+ sessionNode5.subject)

sessionNode6=SessionNode(resources=resources)
print('test with resources: '+ sessionNode6.subject)


test with nodes: mySession does not look like a valid URI, trying to serialize this will break.
test with nodes: 4499de21-f13f-11ec-a70d-c8f75043ce59 does not look like a valid URI, trying to serialize this will break.
test with resources: 449a530d-f13f-11ec-815d-c8f75043ce59 does not look like a valid URI, trying to serialize this will break.


test with nodes: mySession
test with nodes: 4499de21-f13f-11ec-a70d-c8f75043ce59
test with resources: 449a530d-f13f-11ec-815d-c8f75043ce59


## 3. EXPORT DATA

In [7]:
resourceFolder=os.path.join(sessionPath,'Resources')
sessionNode5.export_resource(resourceFolder)

\Scan-to-BIM repository\geomapi\tests\Samples7\Resources\43be9b1c-f13f-11ec-8e65-c8f75043ce59 does not look like a valid URI, trying to serialize this will break.
\Scan-to-BIM repository\geomapi\tests\Samples7\Resources\43be9b1c-f13f-11ec-8e65-c8f75043ce59\ does not look like a valid URI, trying to serialize this will break.
\Scan-to-BIM repository\geomapi\tests\Samples7\Resources\43be9b1c-f13f-11ec-8e65-c8f75043ce59\.ply does not look like a valid URI, trying to serialize this will break.
d:\Scan-to-BIM repository\geomapi\tests\Samples7\Resources\43be9b1c-f13f-11ec-8e65-c8f75043ce59\.ply does not look like a valid URI, trying to serialize this will break.
\Scan-to-BIM repository\geomapi\tests\Samples7\Resources\43be9b1c-f13f-11ec-8e65-c8f75043ce59.ply does not look like a valid URI, trying to serialize this will break.
d:\Scan-to-BIM repository\geomapi\tests\Samples7\Resources\43be9b1c-f13f-11ec-8e65-c8f75043ce59.ply does not look like a valid URI, trying to serialize this will break.

## 4. CREATE RDF GRAPHS 

In [8]:
sessionGraph=sessionNode5.to_graph(graphPath, save=True)
print(sessionGraph.serialize())

@prefix e57: <http://libe57.org#> .
@prefix v4d: <https://w3id.org/v4d/core#> .

<4499de21-f13f-11ec-a70d-c8f75043ce59> a "<class 'geomapi.nodes.sessionnode.SessionNode'>" ;
    e57:cartesianBounds """[-1.16820610e+01  7.79959866e+04 -1.17144113e+01  1.62223097e+05
 -3.75158827e+00  5.10806510e+01]""" ;
    e57:cartesianTransform """[[1.         0.         0.         8.09790678]
 [0.         1.         0.         3.80675837]
 [0.         0.         1.         0.88035253]
 [0.         0.         0.         1.        ]]""" ;
    v4d:linkedSubjects "['43be9b1c-f13f-11ec-8e65-c8f75043ce59', '43cb15e5-f13f-11ec-a718-c8f75043ce59', '4426ccd7-f13f-11ec-bab4-c8f75043ce59']" ;
    v4d:orientedBounds """[[ 1.52193051e+01 -2.09293550e+01 -2.07175653e+00]
 [ 7.80061468e+04  1.62214824e+05  4.50607285e+01]
 [-1.48406610e+01 -6.47778610e+00 -5.39298974e+00]
 [ 1.45372471e+01 -2.06036772e+01  5.51855517e+00]
 [ 7.79754048e+04  1.62229601e+05  4.93298070e+01]
 [-1.55227190e+01 -6.15210829e+00  2.19732

In [9]:
resourceGraphPath=os.path.join(sessionPath,'resourceGraph.ttl')
resourceGraph=tl.nodes_to_graph(nodelist=nodeList,graphPath=resourceGraphPath, save=True)
print(resourceGraph.serialize())

@prefix e57: <http://libe57.org#> .
@prefix exif: <http://www.w3.org/2003/12/exif/ns#> .
@prefix gom: <https://w3id.org/gom#> .
@prefix openlabel: <https://www.asam.net/index.php?eID=dumpFile&t=f&f=3876&token=413e8c85031ae64cc35cf42d0768627514868b2f#> .
@prefix v4d: <https://w3id.org/v4d/core#> .

<43be9b1c-f13f-11ec-8e65-c8f75043ce59> a "<class 'geomapi.nodes.meshnode.MeshNode'>" ;
    e57:cartesianBounds """[7.79770000e+04 7.79952969e+04 1.62204000e+05 1.62222000e+05
 4.42299995e+01 5.04599991e+01]""" ;
    e57:cartesianTransform """[[1.00000000e+00 0.00000000e+00 0.00000000e+00 7.79862707e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.62213175e+05]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 4.71473521e+01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]]""" ;
    e57:pointCount "4735" ;
    v4d:faceCount "9581" ;
    v4d:name "mesh" ;
    v4d:orientedBounds """[[7.79831774e+04 1.62203744e+05 4.43347990e+01]
 [7.79959866e+04 1.62214984e+05 4.41869699e+01]
 [

In [10]:
combinedList=nodeList + [sessionNode5]
print(combinedList)
combinedGraphPath=os.path.join(sessionPath,'combinedGraph.ttl')
combinedGraph=tl.nodes_to_graph(nodelist=combinedList,graphPath=combinedGraphPath, save=True)
print(combinedGraph.serialize())

[<geomapi.nodes.meshnode.MeshNode object at 0x000001EA98EC7280>, <geomapi.nodes.imagenode.ImageNode object at 0x000001EA98EC71F0>, <geomapi.nodes.pointcloudnode.PointCloudNode object at 0x000001EA98EC7370>, <geomapi.nodes.sessionnode.SessionNode object at 0x000001EA98E98940>]
@prefix e57: <http://libe57.org#> .
@prefix exif: <http://www.w3.org/2003/12/exif/ns#> .
@prefix gom: <https://w3id.org/gom#> .
@prefix openlabel: <https://www.asam.net/index.php?eID=dumpFile&t=f&f=3876&token=413e8c85031ae64cc35cf42d0768627514868b2f#> .
@prefix v4d: <https://w3id.org/v4d/core#> .

<43be9b1c-f13f-11ec-8e65-c8f75043ce59> a "<class 'geomapi.nodes.meshnode.MeshNode'>" ;
    e57:cartesianBounds """[7.79770000e+04 7.79952969e+04 1.62204000e+05 1.62222000e+05
 4.42299995e+01 5.04599991e+01]""" ;
    e57:cartesianTransform """[[1.00000000e+00 0.00000000e+00 0.00000000e+00 7.79862707e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.62213175e+05]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 4.7147352