# READING MESH REFERENCE DATA FOR POSE MAPPING
In this notebook, we evaluate the RDF GRAPHS in a session repository.
For every MESHNODE resource, a MESHNODE metadata class is created and its data is loaded. 
The following files will be imported and represented in memory
>meshnodelist[]

>This codebase operates on the scan2bim2.yml environment (python 3.8)

In [12]:
# import APIs
import rdflib
from rdflib import Graph
from rdflib import URIRef, BNode, Literal
from rdflib.namespace import CSVW, DC, DCAT, DCTERMS, DOAP, FOAF, ODRL2, ORG, OWL, \
                           PROF, PROV, RDF, RDFS, SDO, SH, SKOS, SOSA, SSN, TIME, \
                           VOID, XMLNS, XSD
import os.path, time
import importlib
import PIL
import PIL.Image as PILimage
import numpy as np
import open3d as o3d

#IMPORT MODULES
from context import geomapi 
from geomapi.nodes import *
import geomapi.utils as ut
from geomapi.utils import geometryutils as gmu
import geomapi.tools as tl

In [ ]:
%load_ext autoreload

In [ ]:
%autoreload 2

## 1. INITIALIZE SESSION

In [13]:
## INPUTS
projectPath= os.path.abspath(os.path.join(os.getcwd(), os.pardir))+"\\tests"#"D:\\Data\\2018-06 Werfopvolging Academiestraat Gent" 
sessionPath = projectPath + "\\Samples5" #"K:\Projects\2025-03 Project FWO SB Jelle\7.Data\21-11 House Maarten\RAW data\session_22-03-13 canon

## 2. READ AND MERGE All THE RDF GRAPHS IN THE SESSION (save for feature.ttl files)

In [15]:
## read all graph files in a session and merge them
allSessionFilePaths=ut.get_list_of_files(sessionPath) 
rdfGraphPaths=[]

# collect all RDF graphs in the session
sessionGraph = Graph()
for path in allSessionFilePaths:        
    if 'meshGraph' in path: 
        rdfGraphPaths.append(path)
        sessionGraph.parse(path)     
        print('Graph found with '+str(len(sessionGraph)) +' triples')

Graph found with 10 triples


In [16]:
#test
print(sessionGraph.serialize())

@prefix e57: <http://libe57.org#> .
@prefix openlabel: <https://www.asam.net/index.php?eID=dumpFile&t=f&f=3876&token=413e8c85031ae64cc35cf42d0768627514868b2f#> .
@prefix v4d: <https://w3id.org/v4d/core#> .

<http://week22> a "<class 'geomapi.meshnode.MeshNode'>" ;
    e57:cartesianBounds """[-37.36532974 106.94235229  16.87863541 130.69406128   0.71651864
  23.73304558]""" ;
    e57:cartesianTransform """[[ 1.          0.          0.         27.45802746]
 [ 0.          1.          0.         72.81697582]
 [ 0.          0.          1.          4.60116236]
 [ 0.          0.          0.          1.        ]]""" ;
    e57:pointCount "330263" ;
    v4d:accuracy "0.05" ;
    v4d:faceCount "485077" ;
    v4d:orientedBounds """[[-1.96025705e+01  1.65884170e+02  2.22874728e+01]
 [ 1.22465481e+02  1.23859452e+02  2.29468259e+01]
 [-5.26111776e+01  5.43129171e+01  2.33762909e+01]
 [-1.95654721e+01  1.65648765e+02 -7.09825518e-01]
 [ 8.94939722e+01  1.20527931e+01  1.03834556e+00]
 [-5.25740791e+0

# 3. An MeshNode is created per image subject in the RDF Graph

In [22]:
nodelist=tl.graph_to_nodes(sessionGraph,sessionPath=sessionPath)
print (str(len(nodelist))+' Nodes succesfully created from the session!')

1 Nodes succesfully created from the session!


## 4. IMPORT O3D.Trianglemesh
import o3d.geometry.trianglemesh for each pointcloudnode if present

In [18]:
counter=0
for node in nodelist:
    if node.get_geometry():
        print(str(node.name)+' succusfully imported')
        counter +=1

print (str(counter)+' of '+str(len(nodelist))+ ' MeshNodes have their o3d.geometry.trianglemesh imported!')

week22 succusfully imported
1 of 1 MeshNodes have their o3d.geometry.trianglemesh imported!


In [21]:
nodelist[0].visualize()