# GRAPH TO SESSION
In this notebook, we evaluate the RDF GRAPHS in a session repository.
For every resource, a NODE metadata class is created and its data is loaded. 
The following variables are created
>sessionNode

>This codebase operates on the scan2bim2.yml environment (python 3.8)

In [601]:
#IMPORT PACKAGES
from rdflib import Graph
import os.path
import importlib
import numpy as np
import open3d as o3d
import sys
#IMPORT MODULES
from context import geomapi 
from geomapi.nodes import *
from geomapi.utils import *
import geomapi.tools as tl

In [602]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [603]:
%autoreload 2

## 1. INITIALIZE SESSION

In [604]:
## INPUTS
projectPath= os.path.abspath(os.path.join(os.getcwd(), os.pardir))+"\\tests"#"D:\\Data\\2018-06 Werfopvolging Academiestraat Gent" 
sessionPath = projectPath + "\\Samples7" #"K:\Projects\2025-03 Project FWO SB Jelle\7.Data\21-11 House Maarten\RAW data\session_22-03-13 canon
remark1='remark'

graphPath1=sessionPath+"\\sessionGraph.ttl"
graphPath2=sessionPath+"\\resourceGraph.ttl"
graphPath3=sessionPath+"\\combinedGraph.ttl"

## 2. READ AND MERGE All THE RDF GRAPHS IN THE SESSION (save for feature.ttl files)

In [605]:
#Parse graphs
graph1=Graph().parse(graphPath1)  
graph2=Graph().parse(graphPath2)  
graph3=Graph().parse(graphPath3)  

In [606]:
#test
print(graph1.serialize())

@prefix e57: <http://libe57.org#> .
@prefix v4d: <https://w3id.org/v4d/core#> .

<file:///d:/Scan-to-BIM%20repository/geomapi/tests/Samples7/4499de21-f13f-11ec-a70d-c8f75043ce59> a "<class 'geomapi.nodes.sessionnode.SessionNode'>" ;
    e57:cartesianBounds """[-1.16820610e+01  7.79959866e+04 -1.17144113e+01  1.62223097e+05
 -3.75158827e+00  5.10806510e+01]""" ;
    e57:cartesianTransform """[[1.         0.         0.         8.09790678]
 [0.         1.         0.         3.80675837]
 [0.         0.         1.         0.88035253]
 [0.         0.         0.         1.        ]]""" ;
    v4d:linkedSubjects "['43be9b1c-f13f-11ec-8e65-c8f75043ce59', '43cb15e5-f13f-11ec-a718-c8f75043ce59', '4426ccd7-f13f-11ec-bab4-c8f75043ce59']" ;
    v4d:orientedBounds """[[ 1.52193051e+01 -2.09293550e+01 -2.07175653e+00]
 [ 7.80061468e+04  1.62214824e+05  4.50607285e+01]
 [-1.48406610e+01 -6.47778610e+00 -5.39298974e+00]
 [ 1.45372471e+01 -2.06036772e+01  5.51855517e+00]
 [ 7.79754048e+04  1.62229601e+05 

## 2. CREATE DATA NODES


In [607]:
#create sessionnodes from graphs
sessionnode1a=SessionNode(graph=graph1,graphPath=graphPath1,getResource=True, remark1=remark1)
print(sessionnode1a.subject)

# #create sessionnodes from graphPaths
sessionnode1b=SessionNode(graphPath=graphPath1,getResource=True, remark1=remark1)
print(sessionnode1b.subject)

43be9b1c-f13f-11ec-8e65-c8f75043ce59 not in graph
43cb15e5-f13f-11ec-a718-c8f75043ce59 not in graph
4426ccd7-f13f-11ec-bab4-c8f75043ce59 not in graph
file:///d:/Scan-to-BIM%20repository/geomapi/tests/Samples7/4499de21-f13f-11ec-a70d-c8f75043ce59
43be9b1c-f13f-11ec-8e65-c8f75043ce59 not in graph
43cb15e5-f13f-11ec-a718-c8f75043ce59 not in graph
4426ccd7-f13f-11ec-bab4-c8f75043ce59 not in graph
file:///d:/Scan-to-BIM%20repository/geomapi/tests/Samples7/4499de21-f13f-11ec-a70d-c8f75043ce59


In [608]:
sessionnode2a=SessionNode(graph=graph2,getResource=True, remark1=remark1)
print(sessionnode2a.linkedNodes[0].mesh)
print(sessionnode2a.linkedNodes[2].pcd)

sessionnode2b=SessionNode(graphPath=graphPath2,getResource=True, remark1=remark1)
print(sessionnode2b.linkedNodes[0].mesh)
print(sessionnode2b.linkedNodes[2].pcd)

no sessionSubjects found
No file containing this object's name and extension is found in the sessionfolder
No file containing this object's name and extension is found in the sessionfolder
No file containing this object's name and extension is found in the sessionfolder
None
None
no sessionSubjects found
TriangleMesh with 4735 points and 9581 triangles.
PointCloud with 1000000 points.


In [609]:
sessionnode3a=SessionNode(graph=graph3,getResource=True, remark1=remark1)
print(sessionnode3a.subject)
print(sessionnode3a.linkedNodes[0].mesh)
print(sessionnode3a.linkedNodes[2].pcd)

sessionnode3b=SessionNode(graphPath=graphPath3,getResource=True, remark1=remark1)
print(sessionnode3b.subject)
print(sessionnode3b.linkedNodes[0].mesh)
print(sessionnode3b.linkedNodes[2].pcd)

No file containing this object's name and extension is found in the sessionfolder
No file containing this object's name and extension is found in the sessionfolder
No file containing this object's name and extension is found in the sessionfolder
file:///d:/Scan-to-BIM%20repository/geomapi/tests/Samples7/4499de21-f13f-11ec-a70d-c8f75043ce59
None
None
file:///d:/Scan-to-BIM%20repository/geomapi/tests/Samples7/4499de21-f13f-11ec-a70d-c8f75043ce59
TriangleMesh with 4735 points and 9581 triangles.
PointCloud with 1000000 points.
