# MeshNode
The meshNode class in Geomapi represents the data and metadata of polygonal mesh data. The data itself and methods build upon Open3D TriangleMesh and Trimesh concepts while the metadata builds upon the RDFlib framework:

[http://www.open3d.org/docs/latest/tutorial/Basic/mesh.html#](http://www.open3d.org/docs/latest/tutorial/Basic/mesh.html#) 

[https://trimsh.org/trimesh.base.html](https://trimsh.org/trimesh.base.html)

[https://rdflib.readthedocs.io/](https://rdflib.readthedocs.io/) 

The code below shows how to create a MeshNode from various inputs.

First the geomapi and external packages are imported

In [1]:
#IMPORT PACKAGES
from rdflib import Graph
import os
import numpy as np

#IMPORT MODULES
from context import geomapi #context import for documentation only
from geomapi.nodes import MeshNode

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


## MeshNode Creation

A MeshNode is constructed using the same parameters as the base Node. Please refer to [Node Tutorial](../tutorial/tutorial_nodes.ipynb) For more info about Node Creation

In [ ]:
MeshNode( subject = None,             # (URIRef, optional) : A subject to use as identifier for the Node.
          graph = None,               # (Graph, optional) : An RDF Graph to parse.
          graphPath = None,           # (Path, optional) : The path of an RDF Graph to parse.
          name = None,                # (str, optional) : A name of the Node.
          path = None,                # (Path, optional) : A filepath to a resource.
          timestamp = None,           # (str, optional) : Timestamp for the node.
          resource = None,            # (optional) : Resource associated with the node.
          cartesianTransform = None,  # (np.ndarray, optional) : The (4x4) transformation matrix.
          orientedBoundingBox = None, # (o3d.geometry.OrientedBoundingBox, optional) : The oriented bounding box of the node.
          convexHull = None,          # (o3d.geometry.TriangleMesh, optional) : The convex hull of the node.
          loadResource = False,       # Load the resource at initialization?
        )

#### Ontology link

The MeshNode has 2 new standard properties that are serialized to the graph:

| python name | predicate |
|-----------  |-----------|
| `pointCount` | `geomapi:pointCount` |
| `faceCount` | `geomapi:faceCount` |


## MeshNode Resource

When creating a Node with a resource, it can be done either directly with the resource, or with the path to the resource.

A resource can be a big piece of data, this is why it is not always wanted to load the whole resource at initialization. This is why the `loadResource` parameter is default to `False`

For more info on specific resources, see the corresponding Node type

### Loading The Resource

In [8]:
node = MeshNode(path=r"../../..\tests\testfiles\mesh\railway.obj", loadResource=False)
print("resource before loading:",node.resource)
node.load_resource() # Use specialized node fo each type of resource.
print("resource after loading:",node.resource)

Resource not loaded, but path is defined, call `load_resource()` to access it.
Resource not loaded, but path is defined, call `load_resource()` to access it.
resource before loading: None
resource after loading: TriangleMesh with 21868 points and 25000 triangles.


### Saving The Resource

A Mesh resource can be saved to disk using the `save_resource()` function.
Currently supports: .ply, .obj

In [6]:
node = MeshNode(path=r"../../..\tests\testfiles\mesh\railway.obj", loadResource=True)
node.save_resource(directory=r"../../../tests/testfiles/resources", extension=".ply") # Save the resource to the resourcePath

[Open3D WARNING] This file format currently does not support writing textures and uv coordinates. Consider using .obj


True

## MeshNode Transformation

Since every nod has a cartesian transform, it can be transformed using the `node.transform()` function.

The transformation also updates the `convexHull` and `orientedBoundingBox`.

Furthermore, if the MeshNode has a resource, that resource is also transformed.

In [ ]:
node = MeshNode()
print(node.cartesianTransform)
transformation = np.array([[0,0,1,0],[0,1,0,0],[1,0,0,0],[0,0,0,1]])
node.transform(transformation=transformation)
print("applying transformation: (-1)")
print(node.cartesianTransform,"\n")

node = MeshNode()
rotation = np.array([90,0,0]) #eulers in degrees
node.transform(rotation=rotation)
print("applying rotation: (90,0,0)")
print(node.cartesianTransform,"\n")

node = MeshNode()
translation = np.array([1,2,3])
node.transform(translation=translation)
print("applying translation: (1,2,3)")
print(node.cartesianTransform)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
applying transformation: (-1)
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]] 

applying rotation: (90,0,0)
[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]] 

applying translation: (1,2,3)
[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]


## MeshNode Visualisation

When a MeshNode has a resource, the `show()` function displays the mesh using either open3d or Trimesh, depending on the workspace.

Use the `inline = True` parameter to display the mesh using the Trimesh viewer in your jupyter notebook file. Otherwise the function opens a new python window to display the open3d viewer

In [ ]:
node = MeshNode()
node.show(inline=True) # The standard node has no resource to display

## Further reading

Please refer to the full [API documentation](../geomapi/geomapi.nodes.meshnode.rst) of the Node class for more details about the functionality